package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.jbo.RowSetIterator;

import xxazor.oracle.apps.per.documents.utils.Utils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentsAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public DocumentsAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxazor.oracle.apps.per.documents.server", /* package name */
      "DocumentsAMLocal" /* Configuration Name */);
    }

    /**
    public void initDocumentTypesVO(){
        DocumentTypesVOImpl vo = getDocumentTypesVO1();
        if(!vo.isPreparedForExecution()){
         vo.executeQuery();
        }
        String [][] getval = Utils.getDocuments();
        for(int i=0;i<getval.length;i++){
                System.out.println(getval[i][0]);
                DocumentTypesVORowImpl row = (DocumentTypesVORowImpl)vo.createRow();
                row.setcode(getval[i][0]);
                row.setmeaning(getval[i][1]);
                vo.insertRow(row);
        }
        RowSetIterator iter = vo.createRowSetIterator("");
        while(iter.hasNext()){
          DocumentTypesVORowImpl row = (DocumentTypesVORowImpl)iter.next();
          System.out.println("row.getcode()"+row.getcode());
          System.out.println("row.getmeaning()"+row.getmeaning());
        }
    }
    **/

    /**Container's getter for DocumentTypesVO1
     */
    public DocumentTypesVOImpl getDocumentTypesVO1() {
        return (DocumentTypesVOImpl)findViewObject("DocumentTypesVO1");
    }

    /**Container's getter for UsersInfoVO1
     */
    public UsersInfoVOImpl getUsersInfoVO1() {
        return (UsersInfoVOImpl)findViewObject("UsersInfoVO1");
    }

    public void filterUserInfo(int userId) {
        UsersInfoVOImpl usersInfoVOImpl = getUsersInfoVO1(); 
        usersInfoVOImpl.filterBy(userId);
    }
}
