package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenTimControlsVORowImpl extends OAViewRowImpl {

    public static final int PERIODO = 0;
    public static final int CONSULTABTN = 1;
    public static final int PERIODOR = 2;
    public static final int CONSULTABTNR = 3;

    /**This is the default constructor (do not remove)
     */
    public GenTimControlsVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Periodo
     */
    public String getPeriodo() {
        return (String) getAttributeInternal(PERIODO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Periodo
     */
    public void setPeriodo(String value) {
        setAttributeInternal(PERIODO, value);
        if("N".equals(value)){
           setPeriodoR(false);
        }else{
           setPeriodoR(true);
        }
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERIODO:
            return getPeriodo();
        case CONSULTABTN:
            return getConsultaBtn();
        case PERIODOR:
            return getPeriodoR();
        case CONSULTABTNR:
            return getConsultaBtnR();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERIODO:
            setPeriodo((String)value);
            return;
        case CONSULTABTN:
            setConsultaBtn((String)value);
            return;
        case PERIODOR:
            setPeriodoR((Boolean)value);
            return;
        case CONSULTABTNR:
            setConsultaBtnR((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute ConsultaBtn
     */
    public String getConsultaBtn() {
        return (String) getAttributeInternal(CONSULTABTN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConsultaBtn
     */
    public void setConsultaBtn(String value) {
        setAttributeInternal(CONSULTABTN, value);
        if("N".equals(value)){
           setConsultaBtnR(false);
        }else{
           setConsultaBtnR(true);
        }
    }

    /**Gets the attribute value for the calculated attribute PeriodoR
     */
    public Boolean getPeriodoR() {
        return (Boolean) getAttributeInternal(PERIODOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PeriodoR
     */
    public void setPeriodoR(Boolean value) {
        setAttributeInternal(PERIODOR, value);
    }

    /**Gets the attribute value for the calculated attribute ConsultaBtnR
     */
    public Boolean getConsultaBtnR() {
        return (Boolean) getAttributeInternal(CONSULTABTNR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConsultaBtnR
     */
    public void setConsultaBtnR(Boolean value) {
        setAttributeInternal(CONSULTABTNR, value);
    }
}
