package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayExecutionsVORowImpl extends OAViewRowImpl {
    public static final int EMPLOYEENUMBER = 0;
    public static final int FULLNAME = 1;
    public static final int ASSIGNMENTACTIONID = 2;
    public static final int ORGANIZATIONID = 3;
    public static final int TAXUNITID = 4;
    public static final int ASSIGNMENTID = 5;
    public static final int PAYROLLACTIONID = 6;
    public static final int EFFECTIVEDATE = 7;
    public static final int DATEEARNED = 8;
    public static final int YEAR = 9;
    public static final int MES = 10;
    public static final int NUMERORECIBO = 11;
    public static final int NUMRECIBOMES = 12;
    public static final int PERIODO = 13;
    public static final int STARTDATE = 14;
    public static final int ENDDATE = 15;
    public static final int PAYROLLID = 16;
    public static final int TIMEPERIODID = 17;
    public static final int PPARUNTYPEID = 18;
    public static final int PAARUNTYPEID = 19;
    public static final int CONSOLIDATIONSETID = 20;
    public static final int ELEMENTSETID = 21;
    public static final int ASSIGNMENTSETID = 22;
    public static final int PERSONID = 23;

    /**This is the default constructor (do not remove)
     */
    public PayExecutionsVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentActionId
     */
    public Number getAssignmentActionId() {
        return (Number) getAttributeInternal(ASSIGNMENTACTIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentActionId
     */
    public void setAssignmentActionId(Number value) {
        setAttributeInternal(ASSIGNMENTACTIONID, value);
    }

    /**Gets the attribute value for the calculated attribute OrganizationId
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute TaxUnitId
     */
    public Number getTaxUnitId() {
        return (Number) getAttributeInternal(TAXUNITID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TaxUnitId
     */
    public void setTaxUnitId(Number value) {
        setAttributeInternal(TAXUNITID, value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentId
     */
    public Number getAssignmentId() {
        return (Number) getAttributeInternal(ASSIGNMENTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentId
     */
    public void setAssignmentId(Number value) {
        setAttributeInternal(ASSIGNMENTID, value);
    }

    /**Gets the attribute value for the calculated attribute PayrollActionId
     */
    public Number getPayrollActionId() {
        return (Number) getAttributeInternal(PAYROLLACTIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PayrollActionId
     */
    public void setPayrollActionId(Number value) {
        setAttributeInternal(PAYROLLACTIONID, value);
    }

    /**Gets the attribute value for the calculated attribute EffectiveDate
     */
    public Date getEffectiveDate() {
        return (Date) getAttributeInternal(EFFECTIVEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EffectiveDate
     */
    public void setEffectiveDate(Date value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute DateEarned
     */
    public Date getDateEarned() {
        return (Date) getAttributeInternal(DATEEARNED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateEarned
     */
    public void setDateEarned(Date value) {
        setAttributeInternal(DATEEARNED, value);
    }

    /**Gets the attribute value for the calculated attribute Year
     */
    public Number getYear() {
        return (Number) getAttributeInternal(YEAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Year
     */
    public void setYear(Number value) {
        setAttributeInternal(YEAR, value);
    }

    /**Gets the attribute value for the calculated attribute Mes
     */
    public Number getMes() {
        return (Number) getAttributeInternal(MES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Mes
     */
    public void setMes(Number value) {
        setAttributeInternal(MES, value);
    }

    /**Gets the attribute value for the calculated attribute Numerorecibo
     */
    public String getNumerorecibo() {
        return (String) getAttributeInternal(NUMERORECIBO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Numerorecibo
     */
    public void setNumerorecibo(String value) {
        setAttributeInternal(NUMERORECIBO, value);
    }

    /**Gets the attribute value for the calculated attribute Numrecibomes
     */
    public Number getNumrecibomes() {
        return (Number) getAttributeInternal(NUMRECIBOMES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Numrecibomes
     */
    public void setNumrecibomes(Number value) {
        setAttributeInternal(NUMRECIBOMES, value);
    }

    /**Gets the attribute value for the calculated attribute Periodo
     */
    public String getPeriodo() {
        return (String) getAttributeInternal(PERIODO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Periodo
     */
    public void setPeriodo(String value) {
        setAttributeInternal(PERIODO, value);
    }

    /**Gets the attribute value for the calculated attribute StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute PayrollId
     */
    public Number getPayrollId() {
        return (Number) getAttributeInternal(PAYROLLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PayrollId
     */
    public void setPayrollId(Number value) {
        setAttributeInternal(PAYROLLID, value);
    }

    /**Gets the attribute value for the calculated attribute TimePeriodId
     */
    public Number getTimePeriodId() {
        return (Number) getAttributeInternal(TIMEPERIODID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TimePeriodId
     */
    public void setTimePeriodId(Number value) {
        setAttributeInternal(TIMEPERIODID, value);
    }

    /**Gets the attribute value for the calculated attribute PpaRunTypeId
     */
    public Number getPpaRunTypeId() {
        return (Number) getAttributeInternal(PPARUNTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PpaRunTypeId
     */
    public void setPpaRunTypeId(Number value) {
        setAttributeInternal(PPARUNTYPEID, value);
    }

    /**Gets the attribute value for the calculated attribute PaaRunTypeId
     */
    public Number getPaaRunTypeId() {
        return (Number) getAttributeInternal(PAARUNTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaaRunTypeId
     */
    public void setPaaRunTypeId(Number value) {
        setAttributeInternal(PAARUNTYPEID, value);
    }

    /**Gets the attribute value for the calculated attribute ConsolidationSetId
     */
    public Number getConsolidationSetId() {
        return (Number) getAttributeInternal(CONSOLIDATIONSETID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConsolidationSetId
     */
    public void setConsolidationSetId(Number value) {
        setAttributeInternal(CONSOLIDATIONSETID, value);
    }

    /**Gets the attribute value for the calculated attribute ElementSetId
     */
    public Number getElementSetId() {
        return (Number) getAttributeInternal(ELEMENTSETID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ElementSetId
     */
    public void setElementSetId(Number value) {
        setAttributeInternal(ELEMENTSETID, value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentSetId
     */
    public Number getAssignmentSetId() {
        return (Number) getAttributeInternal(ASSIGNMENTSETID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentSetId
     */
    public void setAssignmentSetId(Number value) {
        setAttributeInternal(ASSIGNMENTSETID, value);
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case FULLNAME:
            return getFullName();
        case ASSIGNMENTACTIONID:
            return getAssignmentActionId();
        case ORGANIZATIONID:
            return getOrganizationId();
        case TAXUNITID:
            return getTaxUnitId();
        case ASSIGNMENTID:
            return getAssignmentId();
        case PAYROLLACTIONID:
            return getPayrollActionId();
        case EFFECTIVEDATE:
            return getEffectiveDate();
        case DATEEARNED:
            return getDateEarned();
        case YEAR:
            return getYear();
        case MES:
            return getMes();
        case NUMERORECIBO:
            return getNumerorecibo();
        case NUMRECIBOMES:
            return getNumrecibomes();
        case PERIODO:
            return getPeriodo();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case PAYROLLID:
            return getPayrollId();
        case TIMEPERIODID:
            return getTimePeriodId();
        case PPARUNTYPEID:
            return getPpaRunTypeId();
        case PAARUNTYPEID:
            return getPaaRunTypeId();
        case CONSOLIDATIONSETID:
            return getConsolidationSetId();
        case ELEMENTSETID:
            return getElementSetId();
        case ASSIGNMENTSETID:
            return getAssignmentSetId();
        case PERSONID:
            return getPersonId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
