package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerAclarViewVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int PERSONID = 1;
    public static final int ASSIGNMENTID = 2;
    public static final int EFECTIVEDATE = 3;
    public static final int STATUS = 4;
    public static final int PADRE = 5;
    public static final int HIJO = 6;
    public static final int NIETO = 7;
    public static final int APPROVERID = 8;
    public static final int DESCACLARACION = 9;
    public static final int NOTAAPPROVER = 10;
    public static final int CREATEDBY = 11;
    public static final int CREATIONDATE = 12;
    public static final int LASTUPDATEDBY = 13;
    public static final int LASTUPDATEDATE = 14;
    public static final int LASTUPDATELOGIN = 15;
    public static final int EMPLOYEENUMBER = 16;
    public static final int FULLNAME = 17;
    public static final int PADREDESC = 18;
    public static final int HIJODESC = 19;
    public static final int NIETODESC = 20;

    /**This is the default constructor (do not remove)
     */
    public PerAclarViewVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentId
     */
    public Number getAssignmentId() {
        return (Number) getAttributeInternal(ASSIGNMENTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentId
     */
    public void setAssignmentId(Number value) {
        setAttributeInternal(ASSIGNMENTID, value);
    }

    /**Gets the attribute value for the calculated attribute EfectiveDate
     */
    public Date getEfectiveDate() {
        return (Date) getAttributeInternal(EFECTIVEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EfectiveDate
     */
    public void setEfectiveDate(Date value) {
        setAttributeInternal(EFECTIVEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute Padre
     */
    public String getPadre() {
        return (String) getAttributeInternal(PADRE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Padre
     */
    public void setPadre(String value) {
        setAttributeInternal(PADRE, value);
    }

    /**Gets the attribute value for the calculated attribute Hijo
     */
    public String getHijo() {
        return (String) getAttributeInternal(HIJO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Hijo
     */
    public void setHijo(String value) {
        setAttributeInternal(HIJO, value);
    }

    /**Gets the attribute value for the calculated attribute Nieto
     */
    public String getNieto() {
        return (String) getAttributeInternal(NIETO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nieto
     */
    public void setNieto(String value) {
        setAttributeInternal(NIETO, value);
    }

    /**Gets the attribute value for the calculated attribute ApproverId
     */
    public Number getApproverId() {
        return (Number) getAttributeInternal(APPROVERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverId
     */
    public void setApproverId(Number value) {
        setAttributeInternal(APPROVERID, value);
    }

    /**Gets the attribute value for the calculated attribute DescAclaracion
     */
    public String getDescAclaracion() {
        return (String) getAttributeInternal(DESCACLARACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DescAclaracion
     */
    public void setDescAclaracion(String value) {
        setAttributeInternal(DESCACLARACION, value);
    }

    /**Gets the attribute value for the calculated attribute NotaApprover
     */
    public String getNotaApprover() {
        return (String) getAttributeInternal(NOTAAPPROVER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NotaApprover
     */
    public void setNotaApprover(String value) {
        setAttributeInternal(NOTAAPPROVER, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute PadreDesc
     */
    public String getPadreDesc() {
        return (String) getAttributeInternal(PADREDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PadreDesc
     */
    public void setPadreDesc(String value) {
        setAttributeInternal(PADREDESC, value);
    }

    /**Gets the attribute value for the calculated attribute HijoDesc
     */
    public String getHijoDesc() {
        return (String) getAttributeInternal(HIJODESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HijoDesc
     */
    public void setHijoDesc(String value) {
        setAttributeInternal(HIJODESC, value);
    }

    /**Gets the attribute value for the calculated attribute NietoDesc
     */
    public String getNietoDesc() {
        return (String) getAttributeInternal(NIETODESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NietoDesc
     */
    public void setNietoDesc(String value) {
        setAttributeInternal(NIETODESC, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case PERSONID:
            return getPersonId();
        case ASSIGNMENTID:
            return getAssignmentId();
        case EFECTIVEDATE:
            return getEfectiveDate();
        case STATUS:
            return getStatus();
        case PADRE:
            return getPadre();
        case HIJO:
            return getHijo();
        case NIETO:
            return getNieto();
        case APPROVERID:
            return getApproverId();
        case DESCACLARACION:
            return getDescAclaracion();
        case NOTAAPPROVER:
            return getNotaApprover();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case FULLNAME:
            return getFullName();
        case PADREDESC:
            return getPadreDesc();
        case HIJODESC:
            return getHijoDesc();
        case NIETODESC:
            return getNietoDesc();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
