package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PySrsAssetRunVORowImpl extends OAViewRowImpl {
    public static final int ASSIGNMENTSETNAME = 0;
    public static final int ASSIGNMENTSETID = 1;
    public static final int PAYROLLID = 2;

    /**This is the default constructor (do not remove)
     */
    public PySrsAssetRunVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute AssignmentSetName
     */
    public String getAssignmentSetName() {
        return (String) getAttributeInternal(ASSIGNMENTSETNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentSetName
     */
    public void setAssignmentSetName(String value) {
        setAttributeInternal(ASSIGNMENTSETNAME, value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentSetId
     */
    public Number getAssignmentSetId() {
        return (Number) getAttributeInternal(ASSIGNMENTSETID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentSetId
     */
    public void setAssignmentSetId(Number value) {
        setAttributeInternal(ASSIGNMENTSETID, value);
    }

    /**Gets the attribute value for the calculated attribute PayrollId
     */
    public Number getPayrollId() {
        return (Number) getAttributeInternal(PAYROLLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PayrollId
     */
    public void setPayrollId(Number value) {
        setAttributeInternal(PAYROLLID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ASSIGNMENTSETNAME:
            return getAssignmentSetName();
        case ASSIGNMENTSETID:
            return getAssignmentSetId();
        case PAYROLLID:
            return getPayrollId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
