package xxazor.oracle.apps.per.documents.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxazorHrLegalEntityVORowImpl extends OAViewRowImpl {
    public static final int ORGANIZATIONGREID = 0;
    public static final int RAZONSOCIAL = 1;

    /**This is the default constructor (do not remove)
     */
    public XxazorHrLegalEntityVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute OrganizationGreId
     */
    public String getOrganizationGreId() {
        return (String) getAttributeInternal(ORGANIZATIONGREID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationGreId
     */
    public void setOrganizationGreId(String value) {
        setAttributeInternal(ORGANIZATIONGREID, value);
    }

    /**Gets the attribute value for the calculated attribute RazonSocial
     */
    public String getRazonSocial() {
        return (String) getAttributeInternal(RAZONSOCIAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RazonSocial
     */
    public void setRazonSocial(String value) {
        setAttributeInternal(RAZONSOCIAL, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORGANIZATIONGREID:
            return getOrganizationGreId();
        case RAZONSOCIAL:
            return getRazonSocial();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
