CREATE OR REPLACE VIEW APPS.XXAZOR_PER_DOCS_V AS
SELECT XPD.ID            
      ,XPD.PERSON_ID          
      ,XPD.ASSIGNMENT_ID      
      ,XPD.DOC_TYPE           
      ,XPD.EFECTIVE_DATE      
      ,XPD.STATUS             
      ,XPD.APPROVER_ID       
      ,XPD.CREATED_BY        
      ,XPD.CREATION_DATE      
      ,XPD.LAST_UPDATED_BY    
      ,XPD.LAST_UPDATE_DATE   
      ,XPD.LAST_UPDATE_LOGIN  
      ,PAPF.FULL_NAME
      ,XPDT.MEANING DOC_TYPE_MEANING
 FROM XXAZOR_PER_DOCS XPD      
     ,PER_ALL_PEOPLE_F PAPF
     ,XXAZOR_PER_DOC_TYPES XPDT
WHERE PAPF.PERSON_ID = XPD.PERSON_ID 
  AND XPD.CREATION_DATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
  AND XPDT.CODE = XPD.DOC_TYPE
  