CREATE OR REPLACE VIEW XXAZOR_PER_ACLAR_V AS
select XPA.ID           
      ,XPA.PERSON_ID          
      ,XPA.ASSIGNMENT_ID      
      ,XPA.EFECTIVE_DATE      
      ,XPA.STATUS             
      ,XPA.PADRE              
      ,XPA.HIJO               
      ,XPA.NIETO              
      ,XPA.APPROVER_ID        
      ,XPA.DESC_ACLARACION    
      ,XPA.NOTA_APPROVER      
      ,XPA.CREATED_BY         
      ,XPA.CREATION_DATE      
      ,XPA.LAST_UPDATED_BY    
      ,XPA.LAST_UPDATE_DATE   
      ,XPA.LAST_UPDATE_LOGIN  
      ,PAPF.EMPLOYEE_NUMBER
      ,PAPF.FULL_NAME
      ,XPV.MEANING PADRE_DESC
      ,XHV.MEANING HIJO_DESC
      ,XNV.MEANING NIETO_DESC
  from XXAZOR_PER_ACLAR XPA
      ,PER_ALL_PEOPLE_F PAPF
      ,XXAZOR_PER_ACL_P_V XPV
      ,XXAZOR_PER_ACL_H_V XHV
      ,XXAZOR_PER_ACL_N_V XNV
WHERE  XPA.PERSON_ID = PAPF.PERSON_ID
  AND  XPA.EFECTIVE_DATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
  AND  XPA.PADRE = XPV.CODE
  AND  XPA.HIJO = XHV.CODE
  AND  XPA.NIETO = XNV.CODE;