package xxazor.oracle.apps.per.lecbio.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LectorBiometricoAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public LectorBiometricoAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxazor.oracle.apps.per.lecbio.server", /* package name */
      "LectorBiometricoAMLocal" /* Configuration Name */);
    }
}
